name: Build and deploy on azure

on:
  push:
    branches:
      - master

jobs:
  consumers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Navigate to consumers service
        run: cd consumers

      - name: Build and tag image
        run: docker build -t haasregistry.azurecr.io/consumers:${{ github.sha }} .

      - name: Login to registry
        run: docker login haasregistry.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Push image to registry
        run: docker push haasregistry.azurecr.io/consumers:${{ github.sha }}
  
  orders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Navigate to orders service
        run: cd orders

      - name: Build and tag image
        run: docker build -t haasregistry.azurecr.io/orders:${{ github.sha }} .

      - name: Login to registry
        run: docker login haasregistry.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Push image to registry
        run: docker push haasregistry.azurecr.io/orders:${{ github.sha }}

  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Navigate to delivery service
        run: cd delivery

      - name: Build and tag image
        run: docker build -t haasregistry.azurecr.io/delivery:${{ github.sha }} .

      - name: Login to registry
        run: docker login haasregistry.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Push image to registry
        run: docker push haasregistry.azurecr.io/delivery:${{ github.sha }}

  payments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Navigate to payments service
        run: cd payments

      - name: Build and tag image
        run: docker build -t haasregistry.azurecr.io/payments:${{ github.sha }} .

      - name: Login to registry
        run: docker login haasregistry.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Push image to registry
        run: docker push haasregistry.azurecr.io/payments:${{ github.sha }}
